import Foundation

/// Deutsche Namen für die Begriffe der Erkennung.
///
/// Ursprünglich stand hier nichts und ein Fund hieß nach seinem Thema:
/// Besteck war „Geschirr", ein Karton war „Papier". Das war eine bewusste
/// Entscheidung – und eine falsche. Wer ein Ding vor sich hat und die App
/// nennt die Gattung, fühlt sich nicht erkannt, sondern einsortiert.
///
/// Der Inhalt bleibt beim Thema: Gabel und Teller haben dieselbe
/// Nachhaltigkeitsgeschichte, und dafür 1303 Texte zu schreiben wäre
/// tatsächlich Arbeit ohne Ertrag. Nur die Überschrift wird konkret.
///
/// Was hier fehlt, fällt auf den Themennamen zurück. `Tools/namen.swift`
/// listet auf, was noch fehlt.
enum LabelNames {

    static func german(for label: String) -> String? { table[label] }

    static let table: [String: String] = [

        // MARK: Werkstoffe

        "wood_natural": "Holz", "wood_processed": "Holz", "abacus": "Rechenschieber",

        "anvil": "Amboss", "barrel": "Fass", "cage": "Käfig", "fence": "Zaun",
        "gears": "Zahnräder", "horseshoe": "Hufeisen", "hydrant": "Hydrant",
        "keg": "Fass", "manhole": "Kanaldeckel", "mast": "Mast", "pipe": "Rohr",
        "propeller": "Propeller", "pulley": "Flaschenzug", "pylon": "Mast",
        "rim": "Felge", "sword": "Schwert", "wheel": "Rad", "winch": "Winde",

        "aquarium": "Aquarium", "decanter": "Karaffe", "drinking_glass": "Trinkglas",
        "fishbowl": "Goldfischglas", "fishtank": "Aquarium", "hourglass": "Sanduhr",
        "jar": "Schraubglas", "porthole": "Bullauge", "raw_glass": "Glas",
        "stained_glass": "Buntglas", "syringe": "Spritze", "terrarium": "Terrarium",
        "thermometer": "Thermometer", "vase": "Vase", "window": "Fenster",
        "wine_bottle": "Weinflasche",

        "balloon": "Luftballon", "billboards": "Plakatwand", "book": "Buch",
        "bookshelf": "Bücherregal", "calendar": "Kalender", "cardboard_box": "Karton",
        "carton": "Karton", "cassette": "Kassette", "cd": "CD",
        "chalkboard": "Tafel", "christmas_decoration": "Weihnachtsschmuck",
        "decoration": "Schmuck", "diskette": "Diskette", "document": "Dokument",
        "easel": "Staffelei", "envelope": "Umschlag", "flipchart": "Flipchart",
        "gift": "Geschenk", "library": "Bibliothek", "magazine": "Zeitschrift",
        "map": "Landkarte", "matzo": "Matze", "newspaper": "Zeitung",
        "paper_bag": "Papiertüte", "printed_page": "Druckseite", "receipt": "Kassenbon",
        "record": "Schallplatte", "red_envelope": "Umschlag", "sticky_note": "Haftnotiz",
        "whiteboard": "Whiteboard", "wreath": "Kranz",

        "apron": "Schürze", "backpack": "Rucksack", "bag": "Tasche",
        "baseball_hat": "Basecap", "basket_container": "Korb", "bathrobe": "Bademantel",
        "beanie": "Mütze", "bedding": "Bettwäsche", "bib": "Lätzchen",
        "boot": "Stiefel", "bowtie": "Fliege", "briefcase": "Aktentasche",
        "cloak": "Umhang", "clothing": "Kleidung", "cowboy_hat": "Cowboyhut",
        "curtain": "Vorhang", "diaper": "Windel", "earmuffs": "Ohrenschützer",
        "fedora": "Filzhut", "flipper": "Schwimmflosse", "footwear": "Schuhwerk",
        "glove": "Handschuh", "glove_other": "Handschuh", "goggles": "Schutzbrille",
        "gown": "Robe", "hammock": "Hängematte", "hardhat": "Schutzhelm",
        "hat": "Hut", "headgear": "Kopfbedeckung", "helmet": "Helm",
        "high_heel": "Pumps", "hoodie": "Kapuzenpulli", "jacket": "Jacke",
        "jeans": "Jeans", "kilt": "Kilt", "kimono": "Kimono",
        "lab_coat": "Kittel", "leash": "Leine", "leotard": "Gymnastikanzug",
        "loafer": "Slipper", "luggage": "Gepäck", "military_uniform": "Uniform",
        "mitten": "Fäustling", "moccasin": "Mokassin", "necktie": "Krawatte",
        "parachute": "Fallschirm", "pillow": "Kissen", "poncho": "Poncho",
        "purse": "Handtasche", "sack": "Sack", "sandal": "Sandale",
        "sari": "Sari", "scarf": "Schal", "shoes": "Schuhe",
        "sneaker": "Turnschuh", "sock": "Socke", "sombrero": "Sombrero",
        "stuffed_animals": "Kuscheltier", "suit": "Anzug", "suitcase": "Koffer",
        "sunhat": "Sonnenhut", "swimsuit": "Badeanzug", "tent": "Zelt",
        "textile": "Stoff", "tuxedo": "Smoking", "umbrella": "Regenschirm",
        "wallet": "Geldbörse", "wedding_dress": "Brautkleid", "wetsuit": "Neoprenanzug",

        "balloon_hotair": "Heißluftballon", "blocks": "Bauklötze", "bottle": "Flasche",
        "bucket": "Eimer", "chewing_gum": "Kaugummi", "cigar": "Zigarre",
        "cigarette": "Zigarette", "container": "Behälter", "crate": "Kiste",
        "frisbee": "Frisbee", "gas_mask": "Gasmaske", "jug": "Kanne",
        "kite": "Drachen", "lifejacket": "Schwimmweste", "lifesaver": "Rettungsring",
        "lighter": "Feuerzeug", "pacifier": "Schnuller",
        "road_safety_equipment": "Absperrung", "safety_vest": "Warnweste",
        "smoking_item": "Raucherzubehör", "straw_drinking": "Trinkhalm",
        "thermos": "Thermoskanne", "toy": "Spielzeug", "train_toy": "Spielzeugeisenbahn",
        "vehicle_toy": "Spielzeugauto",

        // MARK: Werkzeug und Technik

        "axe": "Axt", "broom": "Besen", "caliper": "Messschieber",
        "chainsaw": "Kettensäge", "clothesline": "Wäscheleine",
        "clothespin": "Wäscheklammer", "compass": "Kompass", "cord": "Kabel",
        "corkscrew": "Korkenzieher", "grater": "Reibe", "hammer": "Hammer",
        "knife": "Messer", "ladle": "Schöpfkelle", "machine": "Maschine",
        "mallet": "Holzhammer", "measuring_tape": "Maßband", "mop": "Wischmopp",
        "mousetrap": "Mausefalle", "mower": "Rasenmäher", "paintbrush": "Pinsel",
        "pen": "Stift", "pliers": "Zange", "power_saw": "Säge",
        "rake": "Rechen", "ratchet": "Ratsche", "rolling_pin": "Nudelholz",
        "rope": "Seil", "scissors": "Schere", "screwdriver": "Schraubendreher",
        "sewing": "Näharbeit", "spatula": "Pfannenwender", "sprinkler": "Rasensprenger",
        "sundial": "Sonnenuhr", "tool": "Werkzeug", "toolbox": "Werkzeugkasten",
        "tripod": "Stativ", "typewriter": "Schreibmaschine",
        "watering_can": "Gießkanne", "wheelbarrow": "Schubkarre",
        "whisk": "Schneebesen", "wrench": "Schraubenschlüssel", "yarn": "Garn",

        "binoculars": "Fernglas", "calculator": "Taschenrechner", "camera": "Kamera",
        "circuit_board": "Platine", "clock": "Uhr", "computer": "Computer",
        "computer_keyboard": "Tastatur", "computer_monitor": "Bildschirm",
        "computer_mouse": "Maus", "computer_tower": "Rechner",
        "consumer_electronics": "Elektrogerät", "dashboard": "Armaturenbrett",
        "dial": "Zifferblatt", "drone_machine": "Drohne", "flashlight": "Taschenlampe",
        "headphones": "Kopfhörer", "keypad": "Tastenfeld", "laptop": "Laptop",
        "microphone": "Mikrofon", "microscope": "Mikroskop",
        "optical_equipment": "Optik", "payphone": "Telefonzelle", "phone": "Telefon",
        "printer": "Drucker", "scoreboard": "Anzeigetafel", "solar_panel": "Solarmodul",
        "speakers_music": "Lautsprecher", "stereo": "Stereoanlage",
        "stethoscope": "Stethoskop", "stopwatch": "Stoppuhr",
        "tachometer": "Drehzahlmesser", "telescope": "Teleskop",
        "television": "Fernseher", "thermostat": "Thermostat", "timepiece": "Uhr",
        "turntable": "Plattenspieler", "watch": "Armbanduhr", "weight_scale": "Waage",

        "appliance": "Haushaltsgerät", "blender": "Mixer", "brick_oven": "Steinofen",
        "cookware": "Kochgeschirr", "cutting_board": "Schneidebrett",
        "dishwasher": "Spülmaschine", "electric_fan": "Ventilator",
        "elevator": "Aufzug", "escalator": "Rolltreppe", "fondue": "Fondue",
        "grill": "Grill", "iron_clothing": "Bügeleisen", "jacuzzi": "Whirlpool",
        "juicer": "Entsafter", "kettle": "Wasserkocher", "kitchen_oven": "Backofen",
        "laundry_machine": "Waschmaschine", "microwave": "Mikrowelle",
        "oven": "Ofen", "pan": "Pfanne", "pot_cooking": "Topf",
        "refrigerator": "Kühlschrank", "rotisserie": "Drehspieß",
        "steamer_cookware": "Dampfgarer", "stove": "Herd", "teapot": "Teekanne",
        "toaster": "Toaster", "toaster_oven": "Minibackofen", "treadmill": "Laufband",
        "vacuum": "Staubsauger",

        // MARK: Möbel, Geschirr, Bad

        "armchair": "Sessel", "bed": "Bett", "bench": "Bank",
        "cabinet": "Schrank", "cakestand": "Tortenplatte", "car_seat": "Autositz",
        "chair": "Stuhl", "chair_other": "Stuhl", "chaise": "Liege",
        "closet": "Kleiderschrank", "crib": "Kinderbett", "cubicle": "Arbeitsplatz",
        "desk": "Schreibtisch", "folding_chair": "Klappstuhl", "frame": "Rahmen",
        "furniture": "Möbelstück", "high_chair": "Hochstuhl", "seat": "Sitz",
        "sofa": "Sofa", "stool": "Hocker", "swivel_chair": "Drehstuhl",
        "table": "Tisch",

        "bowl": "Schüssel", "chopsticks": "Stäbchen", "fork": "Gabel",
        "housewares": "Haushaltswaren", "plate": "Teller", "spoon": "Löffel",
        "tableware": "Geschirr", "utensil": "Besteck",

        "cosmetic_tool": "Kosmetikartikel", "eyeglasses": "Brille",
        "jewelry": "Schmuck", "medicine": "Medikament", "sunglasses": "Sonnenbrille",
        "tiara": "Diadem",

        // MARK: Energie, Wasser, Abfall

        "candle": "Kerze", "candlestick": "Kerzenhalter", "chandelier": "Kronleuchter",
        "dam": "Staudamm", "embers": "Glut", "engine_vehicle": "Motor",
        "extinguisher": "Feuerlöscher", "fire": "Feuer", "firecracker": "Knaller",
        "fireplace": "Kamin", "fireworks": "Feuerwerk", "flame": "Flamme",
        "lamp": "Lampe", "lamppost": "Laterne", "lantern": "Laterne",
        "light": "Licht", "light_bulb": "Glühbirne", "matches": "Streichhölzer",
        "pyrotechnics": "Feuerwerk", "smokestack": "Schornstein",
        "sparkler": "Wunderkerze", "watermill": "Wassermühle",
        "wind_turbine": "Windrad", "windmill": "Windmühle",

        "bath": "Badewanne", "bathroom": "Bad", "bathroom_faucet": "Wasserhahn",
        "bathroom_room": "Bad", "coral_reef": "Korallenriff", "creek": "Bach",
        "dock": "Anleger", "fountain": "Brunnen", "geyser": "Geysir",
        "glacier": "Gletscher", "harbour": "Hafen", "ice": "Eis",
        "iceberg": "Eisberg", "kitchen_faucet": "Wasserhahn", "kitchen_sink": "Spüle",
        "lake": "See", "liquid": "Flüssigkeit", "ocean": "Meer",
        "pier": "Steg", "pool": "Becken", "rainbow": "Regenbogen",
        "river": "Fluss", "shore": "Ufer", "shower": "Dusche",
        "snow": "Schnee", "snowball": "Schneeball", "toilet_seat": "Toilette",
        "underwater": "Unterwasser", "washbasin": "Waschbecken", "water": "Wasser",
        "water_body": "Gewässer", "waterfall": "Wasserfall", "waterways": "Wasserweg",
        "wetland": "Feuchtgebiet",

        // MARK: Pflanzliches

        "almond": "Mandel", "antipasti": "Antipasti", "apple": "Apfel",
        "apricot": "Aprikose", "artichoke": "Artischocke", "arugula": "Rucola",
        "asparagus": "Spargel", "avocado": "Avocado", "banana": "Banane",
        "bean": "Bohne", "beet": "Rote Bete", "bell_pepper": "Paprika",
        "berry": "Beere", "blackberry": "Brombeere", "blueberry": "Heidelbeere",
        "broccoli": "Brokkoli", "cantaloupe": "Zuckermelone", "carrot": "Karotte",
        "cashew": "Cashew", "cauliflower": "Blumenkohl", "celery": "Sellerie",
        "cereal": "Müsli", "cherry": "Kirsche", "chestnut": "Esskastanie",
        "chives": "Schnittlauch", "cilantro": "Koriander", "citrus_fruit": "Zitrusfrucht",
        "coconut": "Kokosnuss", "coffee_bean": "Kaffeebohne", "coleslaw": "Krautsalat",
        "corn": "Mais", "cranberry": "Cranberry",
        "cucumber": "Gurke", "daikon": "Rettich", "dill": "Dill",
        "durian": "Durian", "edamame": "Edamame", "eggplant": "Aubergine",
        "fig": "Feige", "fruit": "Obst", "garlic": "Knoblauch",
        "grain": "Getreide", "grape": "Weintraube", "grapefruit": "Grapefruit",
        "green_beans": "Grüne Bohnen", "guacamole": "Guacamole", "guava": "Guave",
        "habanero": "Habanero", "herb": "Kraut", "honeydew": "Honigmelone",
        "hummus": "Hummus", "jalapeno": "Jalapeño", "kiwi": "Kiwi",
        "kohlrabi": "Kohlrabi", "leek": "Lauch", "lemon": "Zitrone",
        "lemongrass": "Zitronengras", "lettuce": "Salat", "lime": "Limette",
        "lychee": "Litschi", "macadamia": "Macadamia", "mandarine": "Mandarine",
        "mango": "Mango", "mangosteen": "Mangostan", "melon": "Melone",
        "mushroom": "Pilz", "mustard": "Senf", "nectarine": "Nektarine",
        "nut": "Nuss", "oatmeal": "Haferbrei", "onion": "Zwiebel",
        "oranges": "Orange", "papaya": "Papaya", "passionfruit": "Maracuja",
        "pea": "Erbse", "peach": "Pfirsich", "peanut": "Erdnuss",
        "pear": "Birne", "pecan": "Pekannuss", "pepper_veggie": "Paprika",
        "persimmon": "Kaki", "pickle": "Gewürzgurke", "pineapple": "Ananas",
        "pistachio": "Pistazie", "plum": "Pflaume", "pomegranate": "Granatapfel",
        "potato": "Kartoffel", "pumpkin": "Kürbis", "quinoa": "Quinoa",
        "radish": "Radieschen", "rambutan": "Rambutan", "raspberry": "Himbeere",
        "rhubarb": "Rhabarber", "rice": "Reis", "rosemary": "Rosmarin",
        "salad": "Salat", "sauerkraut": "Sauerkraut", "seasonings": "Gewürze",
        "seaweed": "Alge", "seed": "Samen", "sesame": "Sesam",
        "spice": "Gewürz", "spinach": "Spinat", "squash_sport": "Kürbis",
        "starfruit": "Sternfrucht", "strawberry": "Erdbeere",
        "sunflower_seeds": "Sonnenblumenkerne", "tabbouleh": "Taboulé",
        "tapas": "Tapas", "taro": "Taro", "tomato": "Tomate",
        "turmeric": "Kurkuma", "vegetable": "Gemüse", "wasabi": "Wasabi",
        "watermelon": "Wassermelone", "wheat": "Weizen", "zucchini": "Zucchini",

        // MARK: Tierisches

        "anchovy": "Sardelle", "bacon": "Speck", "beef": "Rindfleisch",
        "butter": "Butter", "caprese": "Caprese", "cheese": "Käse",
        "clam": "Muschel", "crab": "Krabbe", "egg": "Ei",
        "fried_chicken": "Brathähnchen", "fried_egg": "Spiegelei",
        "grilled_chicken": "Grillhähnchen", "ham": "Schinken", "honey": "Honig",
        "kebab": "Kebab", "lobster": "Hummer", "mackerel": "Makrele",
        "meat": "Fleisch", "meatball": "Fleischbällchen", "mussel": "Miesmuschel",
        "omelet": "Omelett", "oyster": "Auster", "pepperoni": "Salami",
        "poultry": "Geflügel", "roe": "Rogen", "salami": "Salami",
        "salmon": "Lachs", "sardine": "Sardine", "satay": "Satay",
        "sausage": "Wurst", "scallop": "Jakobsmuschel", "scrambled_eggs": "Rührei",
        "seabass": "Wolfsbarsch", "seafood": "Meeresfrüchte", "shawarma": "Schawarma",
        "shellfish": "Schalentier", "shellfish_prepared": "Meeresfrüchte",
        "snapper": "Schnapper", "souvlaki": "Souvlaki", "spareribs": "Rippchen",
        "steak": "Steak", "sushi": "Sushi", "swordfish": "Schwertfisch",
        "tempura": "Tempura", "teriyaki": "Teriyaki", "trout": "Forelle",
        "tuna": "Thunfisch", "yogurt": "Joghurt", "yolk": "Eigelb",

        // MARK: Verarbeitetes

        "bagel": "Bagel", "baked_goods": "Backware", "baklava": "Baklava",
        "biryani": "Biryani", "biscotti": "Biscotti", "biscuit": "Keks",
        "bread": "Brot", "brownie": "Brownie", "bruschetta": "Bruschetta",
        "burrito": "Burrito", "cake": "Kuchen", "cake_regular": "Kuchen",
        "candy": "Süßigkeit", "candy_cane": "Zuckerstange", "candy_other": "Süßigkeit",
        "caramel": "Karamell", "casserole": "Auflauf", "cheesecake": "Käsekuchen",
        "chocolate": "Schokolade", "chocolate_chip": "Schokostückchen",
        "condiment": "Würzsoße", "cookie": "Plätzchen", "crepe": "Crêpe",
        "croissant": "Croissant", "cupcake": "Cupcake", "curry": "Curry",
        "dessert": "Nachtisch", "donut": "Donut", "dumpling": "Teigtasche",
        "easter_egg": "Osterei", "falafel": "Falafel", "flan": "Flan",
        "food": "Essen", "fries": "Pommes", "frozen": "Tiefgekühltes",
        "frozen_dessert": "Eis", "fruitcake": "Früchtekuchen",
        "gingerbread": "Lebkuchen", "gyoza": "Gyoza", "hamburger": "Burger",
        "hotdog": "Hotdog", "ice_cream": "Eis", "jack_o_lantern": "Kürbislaterne",
        "jello": "Wackelpudding", "jelly": "Gelee", "lollipop": "Lutscher",
        "marshmallow": "Marshmallow", "milkshake": "Milchshake", "muffin": "Muffin",
        "naan": "Naan", "nachos": "Nachos", "paella": "Paella",
        "pancake": "Pfannkuchen", "pasta": "Nudeln", "pastry": "Gebäck",
        "pie": "Kuchen", "pierogi": "Pirogge", "pita": "Pita",
        "pizza": "Pizza", "popcorn": "Popcorn", "popsicle": "Eis am Stiel",
        "pretzel": "Brezel", "pudding": "Pudding", "quesadilla": "Quesadilla",
        "ramen": "Ramen", "risotto": "Risotto", "samosa": "Samosa",
        "sandwich": "Sandwich", "scone": "Scone", "smoothie": "Smoothie",
        "souffle": "Soufflé", "soup": "Suppe", "spaghetti": "Spaghetti",
        "springroll": "Frühlingsrolle", "stir_fry": "Pfannengericht",
        "strudel": "Strudel", "sugar_cube": "Zuckerwürfel", "taco": "Taco",
        "taffy": "Weichkaramell", "tapioca_pearls": "Tapiokaperlen",
        "tiramisu": "Tiramisu", "tortilla": "Tortilla", "waffle": "Waffel",
        "wedding_cake": "Hochzeitstorte", "white_bread": "Weißbrot",
        "wonton": "Wonton",

        // MARK: Getränke

        "beer": "Bier", "bubble_tea": "Bubble Tea", "cocktail": "Cocktail",
        "coffee": "Kaffee", "cup": "Tasse", "drink": "Getränk",
        "hookah": "Wasserpfeife", "juice": "Saft", "liquor": "Spirituose",
        "margarita": "Margarita", "martini": "Martini", "mojito": "Mojito",
        "mug": "Becher", "red_wine": "Rotwein", "sangria": "Sangria",
        "soda": "Limonade", "sparkling_wine": "Sekt", "tea_drink": "Tee",
        "tequila": "Tequila", "white_wine": "Weißwein", "wine": "Wein",

        // MARK: Gebautes

        "agriculture": "Landwirtschaft", "airport": "Flughafen", "alley": "Gasse",
        "apartment": "Wohnhaus", "arch": "Bogen", "arena": "Arena",
        "balcony": "Balkon", "bar": "Bar", "barn": "Scheune",
        "bedroom": "Schlafzimmer", "beehive": "Bienenstock", "belltower": "Glockenturm",
        "birdhouse": "Vogelhaus", "boathouse": "Bootshaus", "brick": "Ziegel",
        "bridge": "Brücke", "building": "Gebäude", "castle": "Burg",
        "cave": "Höhle", "cellar": "Keller", "chimney": "Schornstein",
        "cityscape": "Stadtbild", "classroom": "Klassenzimmer",
        "clock_tower": "Uhrturm", "crosswalk": "Zebrastreifen", "deck": "Terrasse",
        "dining_room": "Esszimmer", "dirt_road": "Feldweg", "dome": "Kuppel",
        "domicile": "Wohnhaus", "door": "Tür", "driveway": "Einfahrt",
        "farm": "Bauernhof", "flagpole": "Fahnenmast", "garage": "Garage",
        "garden": "Garten", "gargoyle": "Wasserspeier", "gazebo": "Pavillon",
        "greenhouse": "Gewächshaus", "hangar": "Hangar", "health_club": "Fitnessstudio",
        "hospital": "Krankenhaus", "house_single": "Haus", "houseboat": "Hausboot",
        "igloo": "Iglu", "interior_room": "Innenraum", "interior_shop": "Ladenraum",
        "kitchen": "Küche", "kitchen_countertop": "Arbeitsplatte",
        "kitchen_room": "Küche", "lighthouse": "Leuchtturm", "living_room": "Wohnzimmer",
        "mailbox": "Briefkasten", "megalith": "Megalith", "monument": "Denkmal",
        "museum": "Museum", "obelisk": "Obelisk", "office_supplies": "Bürobedarf",
        "park": "Park", "parking_lot": "Parkplatz", "path": "Pfad",
        "patio": "Terrasse", "pergola": "Pergola", "playground": "Spielplatz",
        "pole": "Pfosten", "porch": "Veranda", "pyramid": "Pyramide",
        "railroad": "Bahngleis", "restaurant": "Restaurant", "rice_field": "Reisfeld",
        "road": "Straße", "road_other": "Straße", "roof": "Dach",
        "ruins": "Ruine", "scarecrow": "Vogelscheuche", "shed": "Schuppen",
        "sidewalk": "Gehweg", "sign": "Schild", "silo": "Silo",
        "skatepark": "Skatepark", "skyscraper": "Hochhaus", "stadium": "Stadion",
        "stairs": "Treppe", "storefront": "Schaufenster", "street": "Straße",
        "street_sign": "Straßenschild", "structure": "Bauwerk", "tower": "Turm",
        "track_rail": "Gleis", "traffic_light": "Ampel", "trail": "Weg",
        "train_station": "Bahnhof", "tunnel": "Tunnel", "vineyard": "Weinberg",
        "zoo": "Zoo",

        // MARK: Verkehr

        "aircraft": "Flugzeug", "airplane": "Flugzeug", "ambulance": "Rettungswagen",
        "atv": "Quad", "automobile": "Auto", "backhoe": "Bagger",
        "barge": "Lastkahn", "bicycle": "Fahrrad", "boat": "Boot",
        "bodyboard": "Bodyboard", "bulldozer": "Planierraupe", "bus": "Bus",
        "cableway": "Seilbahn", "canoe": "Kanu", "car": "Auto",
        "cart": "Karren", "chairlift": "Sessellift", "convertible": "Cabrio",
        "conveyance": "Fahrzeug", "crane_construction": "Baukran",
        "cruise_ship": "Kreuzfahrtschiff", "crutch": "Krücke",
        "firetruck": "Feuerwehrauto", "forklift": "Gabelstapler",
        "formula_one_car": "Rennwagen", "go_kart": "Gokart",
        "hangglider": "Drachenflieger", "helicopter": "Hubschrauber",
        "ice_skates": "Schlittschuhe", "jeep": "Geländewagen", "jetski": "Jetski",
        "kayak": "Kajak", "limousine": "Limousine", "monorail": "Einschienenbahn",
        "motorcycle": "Motorrad", "motorhome": "Wohnmobil", "oar": "Ruder",
        "police_car": "Polizeiauto", "rickshaw": "Rikscha", "rocket": "Rakete",
        "rollerskates": "Rollschuhe", "rowboat": "Ruderboot", "saddle": "Sattel",
        "sailboat": "Segelboot", "scooter": "Roller", "semi_truck": "Sattelzug",
        "shopping_cart": "Einkaufswagen", "skateboard": "Skateboard",
        "ski_boot": "Skischuh", "ski_equipment": "Skiausrüstung", "sled": "Schlitten",
        "snowboard": "Snowboard", "snowmobile": "Schneemobil",
        "snowshoe": "Schneeschuh", "speedboat": "Motorboot", "sportscar": "Sportwagen",
        "streetcar": "Straßenbahn", "stretcher": "Trage", "stroller": "Kinderwagen",
        "submarine_water": "U-Boot", "surfboard": "Surfbrett", "suv": "Geländewagen",
        "tire": "Reifen", "tractor": "Traktor", "train": "Zug",
        "train_real": "Zug", "tramway": "Straßenbahn", "tricycle": "Dreirad",
        "truck": "Lastwagen", "van": "Transporter", "vehicle": "Fahrzeug",
        "wagon": "Wagen", "warship": "Kriegsschiff", "watercraft": "Wasserfahrzeug",
        "wheelchair": "Rollstuhl", "yacht": "Jacht",

        // MARK: Landschaft

        "aurora": "Polarlicht", "beach": "Strand", "blizzard": "Schneesturm",
        "blue_sky": "Blauer Himmel", "canyon": "Schlucht",
        "celestial_body": "Himmelskörper", "celestial_body_other": "Himmelskörper",
        "cliff": "Klippe", "cloudy": "Bewölkt", "daytime": "Tageslicht",
        "desert": "Wüste", "haze": "Dunst", "hill": "Hügel",
        "island": "Insel", "land": "Land", "lava": "Lava",
        "lightning": "Blitz", "moon": "Mond", "mountain": "Berg",
        "night_sky": "Nachthimmel", "outdoor": "Draußen",
        "rock_climbing": "Klettern", "rocks": "Felsen", "sand": "Sand",
        "sand_dune": "Düne", "sky": "Himmel", "storm": "Sturm",
        "sun": "Sonne", "sunset_sunrise": "Sonnenuntergang",
        "thunderstorm": "Gewitter", "tornado": "Tornado", "volcano": "Vulkan",

        // MARK: Pflanzen und Bäume

        "begonia": "Begonie", "bouquet": "Blumenstrauß", "cactus": "Kaktus",
        "carnation": "Nelke", "chrysanthemum": "Chrysantheme", "clover": "Klee",
        "cornflower": "Kornblume", "daffodil": "Narzisse", "dahlia": "Dahlie",
        "daisy": "Gänseblümchen", "dandelion": "Löwenzahn",
        "decorative_plant": "Zierpflanze", "ferns": "Farn", "flower": "Blume",
        "flower_arrangement": "Gesteck", "grass": "Gras", "holly": "Stechpalme",
        "ivy": "Efeu", "lily": "Lilie", "marigold": "Ringelblume",
        "mistletoe": "Mistel", "moss": "Moos", "orchid": "Orchidee",
        "petunia": "Petunie", "plant": "Pflanze", "poinsettia": "Weihnachtsstern",
        "rose": "Rose", "shrub": "Strauch", "snapdragon": "Löwenmaul",
        "straw_hay": "Stroh", "sunflower": "Sonnenblume", "tulip": "Tulpe",
        "vegetation": "Bewuchs",

        "acorn": "Eichel", "blossom": "Blüte", "bonsai": "Bonsai",
        "branch": "Ast", "christmas_tree": "Weihnachtsbaum",
        "eucalyptus_tree": "Eukalyptus", "evergreen": "Nadelbaum",
        "foliage": "Laub", "forest": "Wald", "jungle": "Dschungel",
        "mangrove": "Mangrove", "maple_tree": "Ahorn", "oak_tree": "Eiche",
        "orchard": "Obstgarten", "palm_tree": "Palme", "sequoia": "Mammutbaum",
        "tree": "Baum", "willow": "Weide",

        // MARK: Instrumente

        "accordion": "Akkordeon", "bell": "Glocke", "bongo_drum": "Bongo",
        "brass_music": "Blechbläser", "cello": "Cello", "clarinet": "Klarinette",
        "drum": "Trommel", "flute": "Querflöte", "guitar": "Gitarre",
        "harp": "Harfe", "musical_instrument": "Instrument",
        "organ_instrument": "Orgel", "piano": "Klavier", "saxophone": "Saxofon",
        "string_instrument": "Streichinstrument", "tambourine": "Tamburin",
        "trombone": "Posaune", "trumpet": "Trompete", "tuba": "Tuba",
        "ukulele": "Ukulele", "violin": "Geige", "woodwind": "Holzblasinstrument",
        "xylophone": "Xylofon",

        // MARK: Sport und Freizeit

        "amusement_park": "Freizeitpark", "archery": "Bogenschießen",
        "athletics": "Leichtathletik", "badminton": "Badminton", "ball": "Ball",
        "ballet": "Ballett", "ballet_dancer": "Ballett", "ballgames": "Ballspiel",
        "barbell": "Langhantel", "baseball": "Baseball",
        "baseball_bat": "Baseballschläger", "basketball": "Basketball",
        "bellydance": "Bauchtanz", "billiards": "Billard", "bleachers": "Tribüne",
        "bowling": "Bowling", "boxing": "Boxen", "breakdancing": "Breakdance",
        "bungee": "Bungeespringen", "camping": "Camping", "carousel": "Karussell",
        "cheerleading": "Cheerleading", "cricket_sport": "Cricket",
        "cycling": "Radfahren", "dancing": "Tanzen", "dartboard": "Dartscheibe",
        "diving": "Tauchen", "dumbbell": "Hantel", "fairground": "Rummelplatz",
        "fencing_sport": "Fechten", "ferris_wheel": "Riesenrad",
        "foosball": "Tischfußball", "football": "Football", "golf": "Golf",
        "golf_ball": "Golfball", "golf_club": "Golfschläger", "golf_course": "Golfplatz",
        "grand_prix": "Autorennen", "gymnastics": "Turnen", "hiking": "Wandern",
        "hockey": "Hockey", "hula": "Hula", "hurdle": "Hürde",
        "ice_skating": "Eislaufen", "juggling": "Jonglieren",
        "kickboxing": "Kickboxen", "kiteboarding": "Kitesurfen",
        "martial_arts": "Kampfsport", "motocross": "Motocross",
        "motorsport": "Motorsport", "nascar": "Autorennen", "paintball": "Paintball",
        "parasailing": "Parasailing", "ping_pong": "Tischtennis", "polo": "Polo",
        "puck": "Puck", "putt": "Putten", "racquet": "Schläger",
        "rafting": "Rafting", "recreation": "Freizeit", "rink": "Eisbahn",
        "rollercoaster": "Achterbahn", "rollerskating": "Rollschuhlaufen",
        "rugby": "Rugby", "samba": "Samba", "sandcastle": "Sandburg",
        "scuba": "Tauchen", "seesaw": "Wippe", "skateboarding": "Skaten",
        "skating": "Eislaufen", "skiing": "Skifahren", "skydiving": "Fallschirmspringen",
        "sledding": "Schlittenfahren", "slide_toy": "Rutsche",
        "snorkeling": "Schnorcheln", "snowboarding": "Snowboarden",
        "snowman": "Schneemann", "soccer": "Fußball", "softball": "Softball",
        "sport": "Sport", "sports_equipment": "Sportgerät", "sumo": "Sumo",
        "surfing": "Surfen", "swimming": "Schwimmen", "swing_playground": "Schaukel",
        "tennis": "Tennis", "trampoline": "Trampolin", "volleyball": "Volleyball",
        "wakeboarding": "Wakeboarden", "waterpolo": "Wasserball",
        "watersport": "Wassersport", "windsurfing": "Windsurfen",
        "winter_sport": "Wintersport", "workout": "Training", "wrestling": "Ringen",
        "yoga": "Yoga",

        // MARK: Tiere
        //
        // Hunderassen behalten ihren geläufigen deutschen Namen; wo es keinen
        // gibt, bleibt der internationale stehen. „Jack-Russell-Terrier" sagt
        // mehr als „Hund".

        "adult_cat": "Katze", "alligator_crocodile": "Krokodil", "angelfish": "Kaiserfisch",
        "animal": "Tier", "ant": "Ameise", "arachnid": "Spinnentier",
        "arthropods": "Gliederfüßer", "australian_shepherd": "Australian Shepherd",
        "barnacle": "Seepocke", "barracuda": "Barrakuda", "basenji": "Basenji",
        "basset": "Basset", "beagle": "Beagle", "bear": "Bär",
        "bee": "Biene", "beekeeping": "Imkerei", "bernese_mountain": "Berner Sennenhund",
        "bichon": "Bichon", "bird": "Vogel", "bison": "Bison",
        "boar": "Wildschwein", "bobcat": "Rotluchs", "bulldog": "Bulldogge",
        "bullfighting": "Stierkampf", "butterfly": "Schmetterling", "camel": "Kamel",
        "canine": "Hundeartiger", "cat": "Katze", "caterpillar": "Raupe",
        "centipede": "Hundertfüßer", "cephalopod": "Kopffüßer", "cetacean": "Wal",
        "chameleon": "Chamäleon", "cheetah": "Gepard", "chihuahua": "Chihuahua",
        "chinchilla": "Chinchilla", "clownfish": "Clownfisch", "cockatoo": "Kakadu",
        "collie": "Collie", "conch": "Fechterschnecke", "corgi": "Corgi",
        "cougar": "Puma", "cow": "Kuh", "coyote_wolf": "Wolf",
        "dachshund": "Dackel", "dalmatian": "Dalmatiner", "deer": "Reh",
        "dinosaur": "Dinosaurier", "doberman": "Dobermann", "dog": "Hund",
        "dolphin": "Delfin", "donkey": "Esel", "dove": "Taube",
        "dragonfly": "Libelle", "dressage": "Dressurreiten", "eagle": "Adler",
        "elephant": "Elefant", "elk": "Elch", "equestrian": "Reitsport",
        "feline": "Katzenartiger", "ferret": "Frettchen", "fish": "Fisch",
        "fishing": "Angeln", "flamingo": "Flamingo", "fox": "Fuchs",
        "frog": "Frosch", "gastropod": "Schnecke", "gecko": "Gecko",
        "gerbil": "Rennmaus", "german_shepherd": "Schäferhund", "giraffe": "Giraffe",
        "goat": "Ziege", "goldfish": "Goldfisch", "greyhound": "Windhund",
        "gull": "Möwe", "guppy": "Guppy", "hamster": "Hamster",
        "hedgehog": "Igel", "heron": "Reiher", "hippopotamus": "Nilpferd",
        "horse": "Pferd", "hound": "Jagdhund", "hummingbird": "Kolibri",
        "hunting": "Jagd", "husky": "Husky", "hyena": "Hyäne",
        "iguana": "Leguan", "insect": "Insekt", "irish_wolfhound": "Irischer Wolfshund",
        "jack_russell_terrier": "Jack-Russell-Terrier", "jellyfish": "Qualle",
        "kangaroo": "Känguru", "kitten": "Kätzchen", "koala": "Koala",
        "koi": "Koi", "ladybug": "Marienkäfer", "lemur": "Lemur",
        "leopard": "Leopard", "lion": "Löwe", "lionfish": "Rotfeuerfisch",
        "lizard": "Eidechse", "llama": "Lama", "lynx": "Luchs",
        "malamute": "Malamute", "malinois": "Malinois", "mammal": "Säugetier",
        "marsupial": "Beuteltier", "mastiff": "Mastiff", "millipede": "Tausendfüßer",
        "mollusk": "Weichtier", "monitor_lizard": "Waran", "moose": "Elch",
        "moth": "Motte", "nest": "Nest", "newfoundland": "Neufundländer",
        "ostrich": "Strauß", "otter": "Otter", "owl": "Eule",
        "panda": "Panda", "parakeet": "Sittich", "parrot": "Papagei",
        "peacock": "Pfau", "pelican": "Pelikan", "penguin": "Pinguin",
        "peregrine": "Wanderfalke", "pig": "Schwein", "pigeon": "Taube",
        "pitbull": "Pitbull", "pomeranian": "Zwergspitz", "poodle": "Pudel",
        "porcupine": "Stachelschwein", "prairie_dog": "Präriehund",
        "puffer_fish": "Kugelfisch", "puffin": "Papageitaucher", "pug": "Mops",
        "python": "Python", "rabbit": "Kaninchen", "raccoon": "Waschbär",
        "raptor": "Greifvogel", "rat": "Ratte", "rattlesnake": "Klapperschlange",
        "raven": "Rabe", "reptile": "Reptil", "retriever": "Retriever",
        "rhinoceros": "Nashorn", "ridgeback": "Ridgeback", "rodent": "Nagetier",
        "rodeo": "Rodeo", "rottweiler": "Rottweiler", "saint_bernard": "Bernhardiner",
        "sandpiper": "Strandläufer", "scarab": "Skarabäus", "schnauzer": "Schnauzer",
        "scorpion": "Skorpion", "seahorse": "Seepferdchen", "seal": "Seehund",
        "sealion": "Seelöwe", "seashell": "Muschel", "setter": "Setter",
        "shark": "Hai", "sheep": "Schaf", "sheepdog": "Hütehund",
        "skunk": "Stinktier", "snail": "Schnecke", "snake": "Schlange",
        "snake_other": "Schlange", "spaniel": "Spaniel", "sparrow": "Spatz",
        "spider": "Spinne", "spiderweb": "Spinnennetz", "squirrel": "Eichhörnchen",
        "starfish": "Seestern", "stingray": "Rochen", "stork": "Storch",
        "sunfish": "Mondfisch", "swan": "Schwan", "terrier": "Terrier",
        "tiger": "Tiger", "toad": "Kröte", "tortoise": "Landschildkröte",
        "toucan": "Tukan", "turtle": "Schildkröte", "ungulates": "Huftier",
        "urchin": "Seeigel", "vizsla": "Vizsla", "vulture": "Geier",
        "walrus": "Walross", "weimaraner": "Weimaraner", "whale": "Wal",
        "woodpecker": "Specht", "worm": "Wurm", "zebra": "Zebra",

        "material": "Gegenstand", "piggybank": "Sparschwein",
        "shipyard": "Werft", "trash_can": "Mülleimer"
    ]
}
